#!/bin/bash
# CollectionBuilder Deployment Script
# Generated by Manage Digital Ingest
#
# IMPORTANT: Run this script FROM your CollectionBuilder project directory!
# cd to your project before running this script!
#
# This script copies the updated CSV file and updates _config.yml

set -e  # Exit on error

echo "=========================================="
echo "CollectionBuilder Deployment Script"
echo "=========================================="
echo ""

# Check if we're in a CollectionBuilder project directory
if [ ! -f "_config.yml" ]; then
    echo "ERROR: _config.yml not found in current directory"
    echo "Please run this script from your CollectionBuilder project root directory"
    exit 1
fi

# Check if _data directory exists
if [ ! -d "_data" ]; then
    echo "Creating _data directory..."
    mkdir -p _data
fi

# Copy the updated CSV file with timestamped name (for record-keeping)
echo "Copying timestamped CSV file to _data directory..."
cp "/Users/BestChlo2016/Documents/GitHub/manage-digital-ingest-flet-CollectionBuilder/storage/temp/file_selector_20251211_173700_8f35bac9/TDPS_CBMetadata_transformed_20251211_173700.csv" "_data/TDPS_CBMetadata_transformed_20251211_173700.csv"

if [ $? -eq 0 ]; then
    echo "✓ Timestamped CSV copied: _data/TDPS_CBMetadata_transformed_20251211_173700.csv"
else
    echo "✗ Failed to copy timestamped CSV file"
    exit 1
fi

# Create a copy with the original filename for deployment
echo "Creating deployment copy with original filename..."
cp "/Users/BestChlo2016/Documents/GitHub/manage-digital-ingest-flet-CollectionBuilder/storage/temp/file_selector_20251211_173700_8f35bac9/TDPS_CBMetadata_transformed_20251211_173700.csv" "_data/TDPS_CBMetadata_transformed.csv"

if [ $? -eq 0 ]; then
    echo "✓ Deployment CSV created: _data/TDPS_CBMetadata_transformed.csv"
else
    echo "✗ Failed to create deployment CSV"
    exit 1
fi

# Update _config.yml
echo ""
echo "Updating _config.yml metadata reference..."

# Check if metadata key exists in _config.yml
if grep -q "^metadata:" "_config.yml"; then
    # Backup _config.yml
    cp _config.yml _config.yml.backup
    echo "  (Backup created: _config.yml.backup)"
    
    # Update the metadata line
    sed -i.tmp 's/^metadata:.*/metadata: TDPS_CBMetadata_transformed/' _config.yml
    rm -f _config.yml.tmp
    
    echo "✓ Updated metadata key in _config.yml"
    echo "  New value: metadata: TDPS_CBMetadata_transformed"
else
    echo "⚠ Warning: 'metadata:' key not found in _config.yml"
    echo "  Please manually add the following line to _config.yml:"
    echo "  metadata: TDPS_CBMetadata_transformed"
fi

echo ""
echo "=========================================="
echo "Deployment Complete!"
echo "=========================================="
echo ""
echo "Next steps:"
echo "1. Review the changes: git diff _config.yml"
echo "2. Test locally: bundle exec jekyll s"
echo "3. Commit and push when ready"
echo ""
